### ISSUE TITLE
Enhanced version code generation

### ISSUE THREAD

**Issue by White-Oak** [White-Oak/space-is-near#64]
VersionCode.java to be generated from gradle and version.code file

**Comment by riseremi** [comment]
What's that?

**Comment by White-Oak** [comment]
@riseremi https://github.com/White-Oak/space-is-near/blob/development/SpaceIsNear/desktop/src/spaceisnear/VersionCode.java -- this file is changed through Gradle build script from gradle.properties file.
I moved on to generate this file from the build script automatically and having version code data in a separate file named version.code.
